name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'say something'
        default: 'Hello'
        required: true
        type: string
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          tmp.txt
          .github/workflows/testOut.yml
        sparse-checkout-cone-mode: false
#    - uses: actions/checkout@v4
#      with:
#        sparse-checkout: |
#           testProjects/csv/my.csv
#        sparse-checkout-cone-mode: true
    - name: where am I
      run: pwd
    - name: whoami
      run: whoami
    - name: list
      run: ls -la
    - name: list deep
      run: ls -la .github/workflows
