name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'say something'
        default: 'Hello'
        required: true
        type: string
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          tmp.txt
          programs/show.pl
          testProjects/csv/my.csv
        sparse-checkout-cone-mode: false
    - name: where am I
      run: pwd
    - name: whoami
      run: whoami
    - name: list
      run: ls -la
    - name: list deep
      run: ls -la programs
    - name: list deep again
      run: ls -la testProjects/csv
